/// Represents a proactive insight generated by the AI.
///
/// Mirrors the server's InsightDto. Category uses enum values:
/// SECURITY, EFFICIENCY, HEALTH, MAINTENANCE, SUSTAINABILITY, PLANNING.
class InsightModel {
  final String id;
  final String content;
  final String category;
  final bool isRead;
  final bool isDismissed;
  final String? generatedAt;
  final String? readAt;

  const InsightModel({
    required this.id,
    required this.content,
    required this.category,
    required this.isRead,
    required this.isDismissed,
    this.generatedAt,
    this.readAt,
  });

  /// Creates an [InsightModel] from a JSON map.
  factory InsightModel.fromJson(Map<String, dynamic> json) {
    return InsightModel(
      id: json['id'] as String,
      content: json['content'] as String? ?? '',
      category: json['category'] as String? ?? 'PLANNING',
      isRead: json['isRead'] as bool? ?? false,
      isDismissed: json['isDismissed'] as bool? ?? false,
      generatedAt: json['generatedAt'] as String?,
      readAt: json['readAt'] as String?,
    );
  }
}

/// Valid insight categories matching the server enum.
class InsightCategory {
  InsightCategory._();

  static const String security = 'SECURITY';
  static const String efficiency = 'EFFICIENCY';
  static const String health = 'HEALTH';
  static const String maintenance = 'MAINTENANCE';
  static const String sustainability = 'SUSTAINABILITY';
  static const String planning = 'PLANNING';

  static const List<String> all = [
    security, efficiency, health, maintenance, sustainability, planning,
  ];
}
